Adding documentation.

diff --git a/bashlock b/bashlock
--- a/bashlock
+++ b/bashlock
@@ -4,6 +4,27 @@
 #  Lockfile managing code.
 
 function bashlock {
+   # Author: Sean Reifschneider <sean+opensource@realgo.com>  
+   # Date: Wed Sep 18, 2013  
+   # License: BSD  
+   # Code/Bugs: https://github.com/realgo/bashlock
+	#
+   # This is a function that implements a lockfile and exclusive access via
+   # that file.  It's a bash function that manages the lockfile via a trap
+   # and is meant to easily be pulled into code to prevent multiple instances
+   # from running at once.
+   #
+   # Getting Started
+   # ---------------
+   #
+   # Copy the "bashlock" function into your code and then call it with a
+   # lockfile name, exit on failure:
+   #
+   #     bashlock /var/run/${0##*/}.pid || exit 1
+   #     [Remainder of script code here]
+   #
+   # Done!
+
 	if [ "$#" -ne 1 ]; then
 		echo 'usage: bashlock [LOCKFILENAME]' 1>&2
 		return 2
